SiteTitle: ReactiveUI
Logo: /assets/img/logo.png
Host: reactiveui.net
LinksUseHttps: true
NetlifyRedirects: true
EditRoot: https://github.com/reactiveui/website/edit/main/input
FontLink: https://fonts.googleapis.com/css2?family=Dosis:wght@700&family=Source+Sans+Pro:wght@300;400&display=swap
sass-blue: "#48bdfe"
sass-indigo: "#bf4bff"
sass-purple: "#bf4bff"
sass-pink: "#ff5885"
sass-red: "#ff5885"
sass-orange: "#e98f00"
sass-yellow: "#e98f00"
sass-green: "#06c0af"
sass-teal: "#06c0af"
sass-cyan: "#06c0af"
sass-primary: "#319af3"
sass-secondary: "#319af3"
sass-success: "#5cb85c"
sass-info: "#319af3"
sass-warning: "#f0ad4e"
sass-danger: "#d9534f"
sass-font-family-sans-serif: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
sass-font-family-serif: "Georgia, \"Times New Roman\", Times, serif;"
sass-font-family-monospace: "\"Roboto Mono\", Menlo, Monaco, Consolas, \"Courier New\", monospace;"
sass-font-family-base: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
