SiteTitle: ReactiveUI
Logo: ./assets/img/logo.png
Host: reactiveui.net
LinksUseHttps: true
NetlifyRedirects: true
NetlifySiteId: Config.FromSetting<string>("NETLIFY_SITE_ID")
NetlifyAccessToken: => Config.FromSetting<string>("NETLIFY_DEPLOY_KEY")
EditRoot: https://github.com/reactiveui/website/edit/main/input
FontLink: "https://fonts.googleapis.com/css2?family=Dosis:wght@700&family=Source+Sans+Pro:wght@300;400&display=swap"
sass-blue: "#48bdfe"
sass-indigo: "#bf4bff"
sass-purple: "#bf4bff"
sass-pink: "#ff5885"
sass-red: "#ff5885"
sass-orange: "#e98f00"
sass-yellow: "#e98f00"
sass-green: "#06c0af"
sass-teal: "#06c0af"
sass-cyan: "#06c0af"
sass-primary: "#319af3"
sass-secondary: "#319af3"
sass-success: "#5cb85c"
sass-info: "#319af3"
sass-warning: "#f0ad4e"
sass-danger: "#d9534f"
sass-font-family-sans-serif: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
sass-font-family-serif: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
sass-font-family-monospace: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
sass-font-family-base: "\"Source Sans Pro\", Helvetica, Arial, sans-serif;"
PostTitle: Blog
PostOrder: 2
ApiOrder: 3
